drop table if exists emprestimo cascade;

drop table if exists pessoa cascade;

create table emprestimo
(
    id               bigint generated by default as identity,
    id_pessoa        bigint         not null,
    data_criacao     date           not null,
    numero_parcelas  int            not null,
    status_pagamento int        not null check (status_pagamento between 0 and 1),
    valor_emprestimo numeric(38, 2) not null,
    primary key (id)
);

create table pessoa
(
    id                   bigint generated by default as identity,
    identificador        varchar(14)    not null,
    nome                 varchar(50)    not null,
    data_nascimento      date           not null,
    tipo_identificador   int        not null check (tipo_identificador between 0 and 3),
    valor_max_emprestimo numeric(38, 2) not null,
    valor_min_mensal     numeric(38, 2) not null,
    primary key (id),
    constraint UniqueAssociado unique (identificador)
);

alter table if exists emprestimo add constraint FKeujhum1ufew05uykqc54c9dg foreign key (id_pessoa) references pessoa
