version: '2.4'

services:
  emprestimodb:
    image: postgres:12-alpine
    container_name: emprestimodb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pg_client
    ports:
      - "5432:5432"
    networks:
      - emprestimo-network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=root"
    ports:
      - "5050:80"
    networks:
      - emprestimo-network

  emprestimo_amqp:
    image: rabbitmq:3.8.3-management
    container_name: emprestimo_amqp
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_ERLANG_COOKIE=secret_pass"
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
    networks:
      - emprestimo-network
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

  ms-emprestimo:
    image: dsousasantos91/ms-emprestimo:1.0.0
    container_name: ms-emprestimo
    restart: always
    environment:
      - "APP_PROFILE=prod"
      - "MS_PAGAMENTO_SERVICE=http://ms-pagamento:8080/api/v1/pagamento"
      - "RABBITMQ_HOST=emprestimo_amqp"
      - "DATABASE_URL=jdbc:postgresql://emprestimodb:5432/postgres"
    ports:
      - "8080:8080"
    depends_on:
      - emprestimodb
      - emprestimo_amqp
    networks:
      - emprestimo-network

  ms-pagamento:
    image: dsousasantos91/ms-pagamento:1.0.0
    container_name: ms-pagamento
    restart: always
    environment:
      - "APP_PROFILE=prod"
      - "RABBITMQ_HOST=emprestimo_amqp"
      - "DATABASE_URL=jdbc:postgresql://emprestimodb:5432/postgres"
    depends_on:
      - emprestimodb
      - emprestimo_amqp
      - ms-emprestimo
    networks:
      - emprestimo-network

networks:
  emprestimo-network:
    name: emprestimo-network
    driver: bridge
