server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    name: emprestimodb
    password: ${PASSWORD_DB:postgres}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${USER_DB:postgres}
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
