spring:
  datasource:
    name: emprestimodb
    password: ${PASSWORD_DB:sa}
    url: ${DATABASE_URL:jdbc:h2:file:~/emprestimo-h2-db;AUTO_SERVER=TRUE}
    username: ${USER_DB:sa}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
