spring:
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: ${APP_PROFILE:dev}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    listener:
      simple:
        default-requeue-rejected: false
    password: ${RABBITMQ_PASSWORD:admin}
    port: ${RABBIT_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    virtual-host: ${RABBIT_VHOST:/}
